<a href="https://colab.research.google.com/github/saincoder404/NLP_lectures/blob/main/game_of_thrones_word2vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
!pip install gensim

In [ ]:
import gensim
import os

In [7]:
import os
import nltk
nltk.download('punkt')
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess

story = []
for filename in os.listdir('data'):
    try:
        with open(os.path.join('data', filename), encoding='utf-8', errors='ignore') as f:
            corups = f.read()

        raw_sent = sent_tokenize(corups)
        for sent in raw_sent:
            story.append(simple_preprocess(sent))
    except Exception as e:
        print(f"Error processing file {filename}: {e}")


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [9]:
story

[['version',
  'history',
  'reedited',
  'by',
  'maelstrom',
  'feast',
  'for',
  'crows',
  'book',
  'four',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'george'],
 ['martin', 'prologue', 'dragons', 'said', 'mollander'],
 ['he',
  'snatched',
  'withered',
  'apple',
  'off',
  'the',
  'ground',
  'and',
  'tossed',
  'it',
  'hand',
  'to',
  'hand'],
 ['throw', 'the', 'apple', 'urged', 'alleras', 'the', 'sphinx'],
 ['he',
  'slipped',
  'an',
  'arrow',
  'from',
  'his',
  'quiver',
  'and',
  'nocked',
  'it',
  'to',
  'his',
  'bowstring'],
 ['should', 'like', 'to', 'see', 'dragon'],
 ['roone',
  'was',
  'the',
  'youngest',
  'of',
  'them',
  'chunky',
  'boy',
  'still',
  'two',
  'years',
  'shy',
  'of',
  'manhood'],
 ['should', 'like', 'that', 'very', 'much'],
 ['and',
  'should',
  'like',
  'to',
  'sleep',
  'with',
  'roseys',
  'arms',
  'around',
  'me',
  'pate',
  'thought'],
 ['he', 'shifted', 'restlessly', 'on', 'the', 'bench'],
 ['by', 'the', 'morrow

In [12]:
model = gensim.models.Word2Vec(
    window = 10,
    min_count = 2
)

In [13]:
model.build_vocab(story)

In [14]:
model.train(story, total_examples=model.corpus_count,epochs=model.epochs)

(6575433, 8625265)

In [16]:
model.wv.most_similar('daenerys')

[('targaryen', 0.809368908405304),
 ('stormborn', 0.800145149230957),
 ('queen', 0.7465435266494751),
 ('martell', 0.7385020852088928),
 ('princess', 0.7347253561019897),
 ('myrcella', 0.7263883948326111),
 ('rhaegar', 0.7212420105934143),
 ('elia', 0.6993552446365356),
 ('aegon', 0.6985810399055481),
 ('unburnt', 0.6985244154930115)]

In [19]:
model.wv.doesnt_match(['jon','robb', 'arya','sansa','bran'])

'jon'

In [20]:
model.wv.doesnt_match(['cersei','jaime','bronn','tyrion'])

'bronn'

In [23]:
model.wv['king']

array([ 3.0248656 , -0.10798474, -0.07704743, -3.490832  , -2.1234899 ,
        3.0474818 ,  1.722814  , -1.2260878 ,  0.5492021 ,  1.9066156 ,
        1.050795  ,  0.16541624, -1.2615935 ,  1.2127389 ,  0.03496513,
       -1.597619  ,  1.5951482 , -1.9002732 , -3.678     , -1.6898291 ,
        4.4363685 ,  1.4365383 , -0.592061  , -1.5618182 ,  0.8675324 ,
        0.6657709 , -2.6393282 ,  1.0906824 , -0.05745761,  0.26558504,
       -0.9079156 ,  2.4006455 , -3.9284985 , -0.7404829 ,  2.073936  ,
        0.1617974 , -0.33074045, -1.5318899 , -0.23878588, -1.2105038 ,
       -0.94203913,  0.21739408,  1.8215415 ,  1.0546753 ,  2.3832898 ,
       -1.0530419 , -0.82439435,  1.6540912 ,  1.8225033 , -0.1776267 ,
        0.58182144, -0.8183112 ,  1.3249258 , -1.2773132 , -1.659293  ,
       -0.86368656,  1.0189884 ,  1.2256433 , -0.10903779, -1.3178306 ,
        1.0680189 , -0.81028086,  1.2182631 ,  2.3213494 , -0.09898835,
        0.97658855, -0.8568673 ,  0.65569484,  0.41939187, -1.63

In [24]:
model.wv.similarity('arya','sansa')

0.85654175

In [25]:
model.wv.similarity('cersei','sansa')

0.755524

In [26]:
model.wv.similarity('arya','cersei')

0.5101964

In [28]:
model.wv.similarity('tywin','sansa')

0.18772982

In [29]:
model.wv.get_normed_vectors()

array([[ 0.05211553, -0.06923325,  0.05902821, ..., -0.20221302,
         0.06327977,  0.13361698],
       [ 0.02359874, -0.01843069,  0.15612225, ..., -0.10755911,
        -0.11599757,  0.10523463],
       [ 0.07730222, -0.12775525, -0.0157951 , ..., -0.06818893,
         0.22304535, -0.0535293 ],
       ...,
       [-0.19543415, -0.00410976, -0.05690809, ...,  0.02395168,
        -0.2001587 ,  0.00918635],
       [ 0.20272434,  0.01450271,  0.1029831 , ..., -0.04564957,
         0.0314519 , -0.01383458],
       [ 0.02399164, -0.02833077,  0.16228737, ..., -0.05637568,
        -0.16907166,  0.03223312]], dtype=float32)

In [30]:
model.wv.get_normed_vectors().shape

(17869, 100)

In [31]:
y = model.wv.index_to_key

In [32]:
y

['the',
 'and',
 'to',
 'of',
 'he',
 'his',
 'was',
 'you',
 'her',
 'in',
 'it',
 'had',
 'that',
 'she',
 'as',
 'with',
 'him',
 'not',
 'but',
 'for',
 'they',
 'is',
 'at',
 'on',
 'said',
 'my',
 'have',
 'be',
 'them',
 'lord',
 'no',
 'from',
 'were',
 'would',
 'me',
 'your',
 'one',
 'all',
 'when',
 'will',
 'ser',
 'if',
 'so',
 'their',
 'could',
 'are',
 'we',
 'man',
 'there',
 'this',
 'up',
 'been',
 'what',
 'did',
 'by',
 'do',
 'men',
 'back',
 'out',
 'more',
 'or',
 'king',
 'who',
 'well',
 'down',
 'than',
 'only',
 'like',
 'jon',
 'some',
 'old',
 'hand',
 'even',
 'too',
 'before',
 'never',
 'tyrion',
 'an',
 'off',
 'know',
 'see',
 'into',
 'made',
 'father',
 'now',
 'eyes',
 'black',
 'told',
 'thought',
 'lady',
 'time',
 'then',
 'how',
 'long',
 'has',
 'might',
 'us',
 'come',
 'where',
 'here',
 'can',
 'through',
 'still',
 'face',
 'head',
 'red',
 'way',
 'page',
 'boy',
 'must',
 'once',
 'good',
 'two',
 'over',
 'little',
 'about',
 'brother'

In [33]:
len(y)

17869

In [34]:
from sklearn.decomposition import PCA

In [36]:
pca = PCA(n_components=3)

In [37]:
x = pca.fit_transform(model.wv.get_normed_vectors())

In [38]:
x[:5]

array([[-0.20664483,  0.5910391 ,  0.01195314],
       [-0.20715335,  0.34773195,  0.06244829],
       [ 0.2592371 ,  0.5541945 ,  0.26561612],
       [-0.04136316,  0.3817622 , -0.10204093],
       [ 0.06740718,  0.52173364,  0.3128348 ]], dtype=float32)

In [39]:
import plotly.express as px

In [48]:
import plotly.express as px
fig = px.scatter_3d(x[:100],x=0, y=1, z=2, color=y[:100])
fig.show()